deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  etcd:
    host:
      - "http://etcd:2379"
    prefix: /apisix
    timeout: 30
  admin:
    admin_key_required: true
    admin_key:
      - name: "admin"
        key: admin-key-aetherweave
        role: admin
    allow_admin:
      - 127.0.0.0/24
      - 172.19.0.0/16
    admin_listen:
      ip: 0.0.0.0
      port: 9180

apisix:
  node_listen: 9080
  enable_ipv6: false

plugin_attr:
  prometheus:
    export_addr:
      ip: 0.0.0.0
      port: 9091
    export_uri: /apisix/prometheus/metrics
