apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
spec:
  # Distributed tracing with Jaeger
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://jaeger:9411/api/v2/spans"
  
  # Prometheus metrics
  metrics:
    enabled: true
  
  # mTLS between services (disabled in local dev, enabled in prod)
  mtls:
    enabled: false
    workloadCertTTL: "24h"
    allowedClockSkew: "15m"
  
  # Access Control (optional)
  accessControl:
    defaultAction: allow
    trustDomain: "public"
  
  # Secrets (configuration to access secrets)
  secrets:
    scopes:
      - storeName: local-secret-store
        defaultAccess: allow
  
  # API logging
  features:
    - name: Resiliency
      enabled: true