global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'docker-dev'
    environment: 'development'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Dapr Placement Service
  - job_name: 'dapr-placement'
    static_configs:
      - targets: ['dapr-placement:9090']

  # Services with Dapr sidecars
  # Each service exposes its metrics on the Dapr metrics port (9090 by default)
  # Uncomment and adapt according to your services
  # - job_name: 'example-service-dapr'
  #   static_configs:
  #     - targets: ['example-service:9090']
  #   metrics_path: '/metrics'

  # RabbitMQ (if prometheus plugin enabled)
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'

  # Redis (with redis_exporter if needed)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # PostgreSQL (with postgres_exporter if needed)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Envoy Gateway (DEPRECATED)
  - job_name: 'envoy'
    static_configs:
      - targets: ['envoy:9901']
    metrics_path: '/stats/prometheus'

  # APISIX Gateway (NEW)
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9091']
    metrics_path: '/apisix/prometheus/metrics'