services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns-local
    command: ["-conf", "/Corefile"]
    volumes:
      - ./coredns/Corefile:/Corefile:ro
      - ./coredns/zones:/zones:ro
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
