stages:
  - generate
  - deploy-docs

variables:
  SERVICE_NAME: user-service

generate-openapi:
  stage: generate
  image: node:20-alpine
  before_script:
    - npm install -g pnpm
  script:
    - pnpm install
    - npm rebuild sqlite3
    - pnpm run generate:openapi
  artifacts:
    paths:
      - openapi.json
    expire_in: 1 hour
  only:
    - develop
    - main
  tags:
    - docker

deploy-docs:
  stage: deploy-docs
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - echo "Copying OpenAPI spec to infrastructure/api-docs/specs/"
    - cp openapi.json ../../infrastructure/api-docs/specs/${SERVICE_NAME}.json
    - cd ../../infrastructure/api-docs
    - git add specs/${SERVICE_NAME}.json
    - git commit -m "Update ${SERVICE_NAME} OpenAPI spec" || echo "No changes to commit"
  dependencies:
    - generate-openapi
  only:
    - develop
    - main
  when: manual
  tags:
    - docker
