networks:
  aetherweave-net:
    external: true
    name: aetherweave-net

services:
  # Dapr sidecar for local development
  # Use this when running the backend with "pnpm run start:dev" on your host machine
  user-service-dapr-dev:
    image: daprio/daprd:1.12.0
    container_name: user-service-dapr-dev
    command:
      [
        "./daprd",
        "-app-id",
        "user-service",
        "-app-port",
        "3000",
        "-dapr-http-port",
        "3500",
        "-dapr-grpc-port",
        "50001",
        "-placement-host-address",
        "dapr-placement:50006",
        "-components-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes:
      - ../../../infrastructure/dapr/components:/components
      - ../../../infrastructure/dapr/config:/config
      - ../../../infrastructure/dapr/secrets:/secrets
    ports:
      - "3500:3500" # Dapr HTTP
      - "50001:50001" # Dapr gRPC
    networks:
      - aetherweave-net
    extra_hosts:
      # Allow Dapr to connect to the app running on host machine
      - "host.docker.internal:host-gateway"
    environment:
      # Tell Dapr to connect to app on host machine
      - APP_HOST=host.docker.internal
    restart: unless-stopped
